{
 "title": "BME280 Exporter",
 "description": "by @spawn2kill - https://github.com/SpaWn2KiLl/bme280-exporter",
 "tags": [ "BME280" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "alias", "query": "label_values(alias)" }
  ]
 },
 "panels": [
  { "title": "$alias", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "alias" },
  {
   "title": "Humidity",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "format": "humidity",
   "valueName": "current",
   "targets": [
    {
     "expr": "bme280_humidity{alias=~\"$alias\"}",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "format": "celsius",
   "valueName": "current",
   "targets": [
    {
     "expr": "bme280_temperature_celsius{alias=~\"$alias\"}",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Pressure",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "bme280_pressure_hpa{alias=~\"$alias\"} / 100",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "humidity" }
   ],
   "targets": [
    {
     "expr": "bme280_humidity{alias=~\"$alias\"}",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "celsius", "label": "Temperature" }
   ],
   "targets": [
    {
     "expr": "bme280_temperature_celsius{alias=~\"$alias\"}",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Pressure",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 9 },
   "yaxes": [
    { "format": "none", "label": "Pa" }
   ],
   "targets": [
    {
     "expr": "bme280_pressure_hpa{alias=~\"$alias\"} / 100",
     "legendFormat": " "
    }
   ]
  }
 ]
}